language: node_js
node_js:
    - "0.11"
    - "0.10"
notifications:
    email: false
matrix:
    allow_failures:
        - node_js: "0.11"
    fast_finish: true
script: "make travis"
after_script: "cat ./coverage/lcov.info | coveralls"
