name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true
          cache: npm
      - name: Install deps
        run: npm ci --include dev
      - name: Run tests
        run: npm test
